version: "3.8"
services:
  duckdb:
    build:
      context: .
      dockerfile: images/duckdb-docker/Dockerfile
    volumes:
      - .:/coralord
    ports:
      - "8001:8001"
    command: /bin/bash -c "python3 /coralord/src/duckdb_python_api.py && tail -f /dev/null"
